### ISSUE TITLE
¿Estado del proyecto?¿Cómo contribuir?

### ISSUE THREAD

**Issue by Kraloz** [bringol/barony_es#2]
Hola! Tengo 2 preguntas

- Cuál es el estado actual del proyecto?
- Cómo se puede contribuir al repositorio? Hay alguna herramienta que se esté utilizando actualmente?

Entiendo que desde el update Life After Death las traducciones hechas hasta el momento quedaron "inutilizadas" ¿Esto es así? No se puede aprovechar el effort hecho anteriormente?

Saludos y feliz año nuevo!!

**Comment by bringol** [comment]
> * Cuál es el estado actual del proyecto?

El proyecto está todavía en desarrollo, aunque pausado por cuestiones personales.


> * Cómo se puede contribuir al repositorio?  Hay alguna herramienta que se esté utilizando actualmente?

Si te refieres a contribuir usando la plataforma github, es cuestión de seguir los procedimientos pertinentes  mediante las solicitudes de cambios. Te dejo este enlace en caso de dudas:
https://docs.github.com/es/get-started/exploring-projects-on-github/contributing-to-a-project?tool=desktop&platform=windows

Especificamente para traducir los archivos, solo hace falta un editor de texto como visual studio code, notepad++ o el que prefieras.

> * Entiendo que desde el update Life After Death las traducciones hechas hasta el momento quedaron "inutilizadas" ¿Esto es así? No se puede aprovechar el effort hecho anteriormente

Por suerte se puede aprovechar el trabajo realizado. Desde Life After Death, los archivos a traducir están distribuidos en forma diferente, pero es una cuestión de adaptar los textos y traducir los nuevos archivos. 

Feliz año.
